name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build ESP32 project
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.3
        target: esp32
        path: 'hello'


